### ISSUE TITLE
Cannot see source while debugging dune built bytecode

### ISSUE THREAD

**Issue by hackwaly** [hackwaly/ocamlearlybird#47]
<img width="424" alt="image" src="https://github.com/hackwaly/ocamlearlybird/assets/540298/5348b36f-c5aa-4de5-8bad-af49507e9b10">

**Comment by sim642** [comment]
Interesting, because I've been using a simple example executable also built by dune and the locations for those frames show up right:
![image](https://github.com/hackwaly/ocamlearlybird/assets/378740/2ab0f9f7-f007-43e5-be2a-c871502e3b79)

There's this commit https://github.com/tizoc/ocamlearlybird/commit/8afcce83ff7a8e7800d45f75b06f335d790a29e1 in a fork. Maybe that has some kind of fix related to this.

**Comment by hackwaly** [comment]
I recall that there was a blocking task was to resolve sources by get infomation from Dune RPC.

**Comment by hackwaly** [comment]
Close as solution given in README
