### ISSUE TITLE
Usage without opam

### ISSUE THREAD

**Issue by eberejustin** [hackwaly/ocamlearlybird#63]
I can't get this to work when I build the executable from sources. Vs code can't find the executable and there doesn't seem to be a setting to point it to  a specific path.

Any way to get around this?

**Comment by sim642** [comment]
`dune install` should be able to install the built files into the right places in your current OCaml paths to make `ocamlearlybird` available in `PATH`. Then VSCode should also be able to launch it.

**Comment by eberejustin** [comment]
it's technically installed. I can run ocamlearlybird on terminal so it's in my system paths. Is there an environment variable i need to set?

**Comment by sim642** [comment]
Which terminal? Your system terminal emulator or VSCode terminal? Maybe VSCode isn't being run with the same environment?
Does VSCode OCaml Platform extension detect your OCaml setup as a sandbox?

There isn't one option to hard-code a path because most people use opam and local opam switches (as opposed to one global OCaml installation) to manage dependencies on a per-project basis. Since different opam switches may have different OCaml versions, they also need different builds of earlybird.

It would be possible to add an override option to VSCode OCaml Platform, which is what needs to find `ocamlearlybird` from VSCode. But I think it wouldn't be a solution to the root problem, rather just a workaround to cover up the issue.
